name: "Update CTF Events"
on:
  schedule:
  - cron: "*/1 * * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "Acquiring permissions"
      run: chmod +x ./ctftime-scraper/main
    - name: "Scraping CTFtime"
      run: ./ctftime-scraper/main 194091
