name: "Update CTF Events"
on:
  schedule:
  - cron: "*/10 * * * *"
  
jobs:
  scrape_ctftime:
    runs-on: ubuntu-latest
    steps:
    - name: "Scraping CTFtime"
      run: ./ctftime-scraper/main 194091
