name: "Update CTF Events"
on:
  schedule:
  - cron: "*/5 * * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "Acquiring permissions"
      run: chmod +x ./ctftime-scraper/main
    - name: "Making output dir"
      run: cd ./ctftime-scraper && mkdir output/
    - name: "Scraping CTFtime"
      run: ./main 194091
