name: "Update CTF Events"
on:
  schedule:
  - cron: "*/5 * * * *" 
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "Acquiring permissions"
      run: |
        cd ctftime-scraper
        chmod +x main
    - name: "Scraping CTFtime"
      run: ./main 194091
    - name: Commit files 
      run: |
        cd ..
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Updated CTF Events"
        git push
