name: "Update CTF Events"
on:
  schedule:
  - cron: "*/5 * * * *" 
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "Acquiring permissions"
      run: chmod +x ./ctftime-scraper/main
    - name: delete old json
      run: rm output/194091.json
    - name: "Scraping CTFtime"
      run: ./ctftime-scraper/main 194091
    - name: show json
      run: cat output/194091.json
    - name: Commit files 
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Updated CTF Events"
        git push
